spring:
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://myapp.com/login/oauth2/code/google"
